from distutils.core import setup

setup(name="Djapps",
      version="0.0.1",
      description="A few utility apps to be used with django in class mode and in appengine mode",
      author="Sri Panyam",
      author_email="sri.panyam@gmail.com",
      url="http://code.google.com/p/djapps/",
      packages = [
          "djapps",
          "djapps/auth",
          "djapps/auth/external",
          "djapps/auth/external/hosts",
          "djapps/auth/external/hosts/fb",
          "djapps/auth/external/hosts/iphone",
          "djapps/auth/external/hosts/myspace",
          "djapps/auth/external/hosts/twitter",
          "djapps/auth/external/sites",
          "djapps/auth/local",
          "djapps/auth/openid",
          "djapps/config",
          "djapps/dynamo",
          "djapps/events",
          "djapps/gaeutils",
          "djapps/gaeutils/contrib",
          "djapps/gaeutils/contrib/auth",
          "djapps/payments",
          "djapps/payments/paypal",
          "djapps/scripts",
          "djapps/static",
          "djapps/static/auth",
          "djapps/static/auth/external",
          "djapps/static/auth/external/fb",
          "djapps/static/auth/external/fb/connect",
          "djapps/static/auth/external/google",
          "djapps/static/auth/external/twitter",
          "djapps/static/auth/external/twitter/icons",
          "djapps/static/flash",
          "djapps/static/flash/history",
          "djapps/static/js",
          "djapps/static/js/eqn",
          "djapps/templates",
          "djapps/templates/auth",
          "djapps/utils",
          "djapps/utils/gae",
          "djapps/utils/static",
          "djapps/utils/static/js",
          "djapps/utils/templates",
          "djapps/utils/templatetags",
      ]
      )
    
